export const dummyItems = [
  {
    seniorId: "1",
    seniorName: "김철수",
    profileUrl: "/img/profile-default.svg",
    address: "서울특별시 강남구 강남동",
    seniorDay: ["월", "목"],
    startTime: "14:00",
    endTime: "18:00",
    careStyle: "일반 돌봄",
    fitness: 98,
  },
  {
    seniorId: "2",
    seniorName: "이영희",
    profileUrl: "/img/profile-default.svg",
    address: "부산광역시 해운대구 해운동",
    seniorDay: ["월", "목"],
    startTime: "14:00",
    endTime: "18:00",
    careStyle: "인지 케어",
    fitness: 98,
  },
  {
    seniorId: "3",
    seniorName: "박민준",
    profileUrl: "/img/profile-default.svg",
    address: "대구광역시 수성구 수정동",
    seniorDay: ["월", "목"],
    startTime: "14:00",
    endTime: "18:00",
    careStyle: "신체 지원",
    fitness: 98,
  },
];

export const dummyItems2 = {
  name: "김철수",
  profileUrl: "/img/profile-default.svg",
  address: "서울특별시 강남구 강남동",
  date: "주 2일 (월, 목)",
  time: "오후 2시~6시",
  request: "추가 요양 보호 가능 여부 문의",
  content: "친근한 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
  salary: "100000 원",
  careList: ["우와우", "와우와", "우와우"],
  phoneNumber: "010-0000-1111",
  addressDetail: "111동 1111호",
};
